# NOTE: It's not a good idea to store secrets in a yaml file in source code.
# The secrets are only base64 encoded in this manifest file (data section) - NOT encrypted!
apiVersion: v1
kind: Secret
metadata:
  name: db-passwords
type: Opaque
data:
  app-password: cfHGejdswa=
  admin-password: acnfheyegJAaHSSJaahbaAD=
