apiVersion: v1
kind: Pod
metadata:
  name: cloud
  labels:
    name: cloud
spec:
  volumes:
    - name: data
      azureFile:
        secretName: secret
        shareName: share
        readOnly: false

  containers:
  - name: myapp
    image: image
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
      - name: data
        mountPath: /data/storage
