apiVersion: v1
kind: Pod
metadata:
  name: host-path
  labels:
    name: host-path
spec:
  volumes:
    - name: docker-socket
      hostPath:
        path: /var/run/docker.sock
        type: Socket

  containers:
  - name: docker
    image: docker
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    command: ["sleep"]
    args: ["100000"]
    volumeMounts:
      - name: docker-socket
        mountPath: /var/run/docker.sock
