apiVersion: v1
kind: Pod
metadata:
  name: nginx-alpine-volume
  labels:
    name: nginx-alpine-volume
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    volumeMounts:
      - name: html
        mountPath: /usr/share/nginx/html
        readOnly: true
    resources:
      limits:
        memory: "128Mi"
        cpu: "50m"
    
  - name: html-updater
    image: alpine
    volumeMounts:
      - name: html
        mountPath: /html
    resources:
      limits:
        memory: "128Mi"
        cpu: "50m"
    command: ["/bin/sh", "-c"]
    args:
      - while true; do date >> /html/index.html;
          sleep 1-; done

  volumes:
    - name: html
      emptyDir: {} #lifecycle tied to pod

# the html-updater container writes to the nginx index.html file, with the current date, the nginx container displays it