apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx
    role: blue
    env: prod
spec:
  type: LoadBalancer
  selector:
    app: nginx
    role: blue
  ports:
  - port: 80
    targetPort: 80
