apiVersion: v1
kind: Service
metadata:
  name: stable-service
  labels:
    app: aspnetcore
spec:
  type: LoadBalancer
  selector:
    app: aspnetcore
  ports:
  - port: <Port>
    targetPort: <Target Port>
