
# defines the ability to get, watch and list K8s services in the default namespace
# if a pod that uses this SA tries to list anything else from the k8s api, it will be forbidden

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: svc-ro
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding # this assigns svc-role to a service account
metadata:
  name: svc-ro
  namespace: default
subjects:
- kind: ServiceAccount
  name: "service-reader"
  namespace: default
roleRef:
  kind: Role 
  name: svc-ro 
  apiGroup: rbac.authorization.k8s.io