apiVersion: v1
kind: Pod
metadata:
  name: web
spec:
  containers:
  # main container
  - name: web-ctr
    image: nigelpoulton/nginxadapter:1.0
    ports:
    - containerPort: 80

  # adapter container:
  # - uses the 'nginx-prometheus-exporter' image to export metrics from nginx and transform it into the prometheus format
  - name: transformer
    image: nginx/nginx-prometheus-exporter
    args: ["-nginx.scrape-uri","http://localhost/nginx_status"]
    ports:
    - containerPort: 9113